### ISSUE TITLE
design an About page template

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-themes#17]
followup of https://github.com/OpenBudget/budgetkey-themes/issues/3#issuecomment-405371839

sections:

- What is this project about ("על הפרוייקט") - 2 paragraphs
- Where is the data from ("מאיפה המידע") - one paragraph
- Who are we ("מי אנחנו") - one paragraph
- Supporters ("גורמים שותפים ותורמים") - icons + list
- How to support ("איך אפשר לתרום") - one paragraph

**Comment by noamoss** [comment]
(I will add real texts next week)

**Comment by mushon** [comment]
Sure thing. Can this design and the notes on InVision wait for next week? Or is there a greater urgency there?

Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

**Comment by noamoss** [comment]
No problem, it can wait for next week.

**Comment by mushon** [comment]
About page is in!
https://projects.invisionapp.com/d/main#/console/7587193/276178413/preview
![item-cards closed-tender](https://user-images.githubusercontent.com/27123/43094490-bf6264ae-8ebb-11e8-8f0a-ff04142a8176.png)

**Comment by noamoss** [comment]
@akariv please see above design. The description includes the sections of the about page - I would like to edit it in a YML file if possible.

**Comment by noamoss** [comment]
(notice we are talking of two about pages: one for social-map and one for  open-procure)

**Comment by akariv** [comment]
http://next.obudget.org/about/?theme=govbuy

Edit the files here to update:
https://github.com/OpenBudget/budgetkey-app-about/tree/master/abouts
