### ISSUE TITLE
design modals

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-themes#18]

**Comment by mushon** [comment]
Modal designed!
https://projects.invisionapp.com/d/main#/console/7587193/310295069/inspect

![image](https://user-images.githubusercontent.com/27123/43093202-18231826-8eb8-11e8-8a84-14df0032f34a.png)

**Comment by noamoss** [comment]
@akariv ready for development, please notice the comment in the invision.

**Comment by noamoss** [comment]
checked on live and approved.
