### ISSUE TITLE
open percure homepage: align box buttons and breaking lines per row

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-themes#19]
box button and header breaking line vertical location should be aligned with other elements in the row (and therefore, set by the lowest point in the row):

![image](https://user-images.githubusercontent.com/3581741/42987585-6d7d8a58-8c02-11e8-8537-cc89b18a125c.png)

**Comment by noamoss** [comment]
@akariv reopening this for two reasons:

1. the blocks (white squares) in each row should be in a common height.

2. you changed the design by putting the buttons on the edge (instead of in the white box). Was that on purpose. 


![image](https://user-images.githubusercontent.com/3581741/43050938-9d005b02-8e19-11e8-8156-8455606d6722.png)

**Comment by akariv** [comment]
That's how the design looks like:

https://projects.invisionapp.com/d/main#/console/7587193/307671317/inspect

![Screen Shot 2018-07-23 at 13.46.03.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/537482f6ebef97b1f959d236/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f06b7191a379ec0c2f57415f4dbe5d4a1f06a3a3dc78e2a436628f540de4d96b5d7c943b19aebdd01eb701ba21dd4d8dbee99850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecb5af54fe34555a5103365f43b.png)

**Comment by noamoss** [comment]
the request to align approved by the graphic department.
