### ISSUE TITLE
add id to questions table element

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-themes#20]
to enable a direct link from the homepage to show an example of usage.

I guess it is a good idea to do so for other gate pages as well.

**Comment by akariv** [comment]
can you share a specific use case?

**Comment by akariv** [comment]
Only scroll table to (almost) top

**Comment by akariv** [comment]
https://next.obudget.org/i/reports/ngo-activity-report/%D7%91%D7%AA%D7%99%20%D7%9B%D7%A0%D7%A1%D7%AA?li=1#questions

**Comment by noamoss** [comment]
@akariv what's the link for usage on `open procure` homepage example? 

https://next.obudget.org/i/tenders/office/516787/4-2010?li=question&theme=govbuy

**Comment by akariv** [comment]
I pasted a sample link above.

https://next.obudget.org/i/tenders/office/516787/4-2010?theme=govbuy#questions

**Comment by noamoss** [comment]
@akariv please leave it open, it is being assigned to me for a reason.

**Comment by akariv** [comment]
What's remaining here?

**Comment by noamoss** [comment]
(a small task for me, to be handled soon)

**Comment by noamoss** [comment]
@akariv will need your help here, as my local env stopped communicating with the server.

**Comment by akariv** [comment]
Okay, what's the small task?

**Comment by noamoss** [comment]
fixed (sent PR, called it 'about-us' instead of 'fix-example'): https://github.com/OpenBudget/openprocure-app-main-page/tree/about-us

**Comment by noamoss** [comment]
(please reassign to me once it is merged, for check)

**Comment by noamoss** [comment]
checked and approved on live
