### ISSUE TITLE
open procure terms pop-ups

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-themes#21]
Noam will provide a terms list to show short explanation for user (i.e. RFI, מכרז פומבי פתוח, etc...) site-wide.

https://docs.google.com/spreadsheets/d/1ztsoslfvEiQS1jSTrivU6chvyAySIIV9tad0L1ZKGj8/edit?usp=sharing

**Comment by noamoss** [comment]
@akariv would you prefer me to edit a yml file directly for that? If so, please provide the file, otherwise, I will hand you a spreadsheet with two columns:
"term","explanation"

**Comment by akariv** [comment]
work with whatever is simpler for you, I'll integrate into the yaml file when I start working on this.

**Comment by noamoss** [comment]
@akariv this is the file link: https://docs.google.com/spreadsheets/d/1ztsoslfvEiQS1jSTrivU6chvyAySIIV9tad0L1ZKGj8/edit?usp=sharing

I will add more values after you implement (please assign to me when ready).
