### ISSUE TITLE
Create Site Footer Markup [2h]

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-themes#3]
Elements to include:

- Usage License
- Github Link
- 3-4 sponsors

**Comment by akariv** [comment]
@noamoss is there a spec for the footer?

**Comment by noamoss** [comment]
@akariv not yet, will wait for my & @mushon meeting and hope to send it.

**Comment by mushon** [comment]
New footer with more details.
After consulting with @shevyk we agreed not to include the logos on every page but to place them on a segment of the about page instead:
https://projects.invisionapp.com/d/main#/console/7587193/308992414/inspect

**Comment by noamoss** [comment]
@mushon ok, it means designing an about page with supporters logos/links section, let's do so on .

Please see my comments on InVision, and reassign to me when done.

**Comment by noamoss** [comment]
@akariv ready for development, please see the notes in the InVision

**Comment by noamoss** [comment]
@akariv 

the current footer is still missing:

- the fixed license text (as provided in the design)
- about
- staff
- privacy policy.

**Comment by noamoss** [comment]
@akariv missing links:

* "CC BY-SA 4.0 של Creative Common" --> https://creativecommons.org/licenses/by-sa/4.0/

* "צויין אחרת" should lead to the about page to the `#licenses` subsection.
https://creativecommons.org/licenses/by-sa/4.0/

* "מדיניות פרטיות" and "תרמו לנו" links are mixed
